version: 2.1

jobs:
  release-github:
    docker:
      - image: linuxgamers/arch-yuzu-build
        user: linuxgamers
    steps:
      - run:
          name: Publishing release to GitHub
          command: |
            git config --global user.name "${GIT_USER}"
            git config --global user.email "${GIT_EMAIL}"
            echo "$(pwd)"
            exit 1
      - persist_to_workspace:
          root: shared
          paths:
            - tag.txt

  release-aur:
    docker:
      - image: linuxgamers/arch-yuzu-build
        user: linuxgamers
    steps:
      - attach_workspace:
          at: /root/project/shared
      - add_ssh_keys:
          fingerprints:
            - "11:77:57:1a:21:81:c1:bd:9c:29:dc:8e:48:b8:bc:d8"
      - run:
          name: Publishing release to AUR
          command: |
            git config --global user.name "${GIT_USER}"
            git config --global user.email "${GIT_EMAIL}"
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H 'aur.archlinux.org' >> ~/.ssh/known_hosts
            export TAG=$(cat shared/tag.txt)
            echo "Publishing release: ${TAG}"
            git clone ssh://aur@aur.archlinux.org/yuzu-mainline-bin.git && cd yuzu-mainline-bin
            wget "https://github.com/linux-gamers/arch-yuzu-mainline/archive/${TAG}.tar.gz"
            VERSION=$(echo ${TAG} | cut -d- -f2)
            sed -i -E "s/_pkgver=.+/_pkgver=${VERSION}/" PKGBUILD
            SHA=$(sha512sum ${TAG}.tar.gz | grep -Eo "(\w+)\s" | cut -d" " -f1)
            sed -i -E "s/sha512sums=.+/sha512sums=\(\'${SHA}\'\)/" PKGBUILD
            ./gensrc.sh
            makepkg -Acsmf
            git commit -am "${TAG}"
            git push

workflows:
  publish-release:
    jobs:
      - release-github:
          filters:
            branches:
              only:
                - ci
      - release-aur:
          requires:
            - release-github
          filters:
            branches:
              only:
                - ci
