version: 2.1

defaults: &defaults
  working_directory: /tmp/work

jobs:
  release-github:
    docker:
      - image: linuxgamers/arch-yuzu-build
    steps:
      - run:
          name: Publishing release to GitHub
          command: |
            mkdir -p shared
            git config --global user.name "${GIT_USER}"
            git config --global user.email "${GIT_EMAIL}"
            git clone https://${GITHUB_TOKEN}@github.com/linux-gamers/arch-yuzu-mainline.git
            cd arch-yuzu-mainline
            git checkout ci
            TAG=$(python -u check_new_release.py)
            if [ -z "$TAG" ]; then echo "No new release to publish" && exit 1; fi
            cd ..
            git clone --recursive -b "mainline-${TAG}" --depth 1 https://github.com/yuzu-emu/yuzu-mainline.git
            cd yuzu-mainline
            git checkout -b "${TAG}" && mkdir build && cd build
            cmake .. -GNinja && ninja -j4
            cd ../../arch-yuzu-mainline && git checkout master
            /bin/cp ../yuzu-mainline/build/bin/yuzu .
            /bin/cp ../yuzu-mainline/build/bin/yuzu-cmd .
            /bin/cp ../yuzu-mainline/dist/yuzu.desktop .
            /bin/cp ../yuzu-mainline/dist/yuzu.svg .
            git add .
            git commit -m "[RELEASE ${TAG}]"
            git push -q https://${GITHUB_TOKEN}@github.com/linux-gamers/arch-yuzu-mainline.git master
            git checkout ci
            python -u release_github.py
            cat "${TAG}" > /tmp/work/shared/tag.txt
      - persist_to_workspace:
          root: shared
          paths:
            - tag.txt

  release-aur:
    docker:
      - image: linuxgamers/arch-yuzu-build
    steps:
      - attach_workspace:
          at: /tmp/work/shared
      - run:
          name: Publishing release to AUR
          command: |
            git config --global user.name "${GIT_USER}"
            git config --global user.email "${GIT_EMAIL}"
            TAG=$(cat shared/tag.txt)
            echo "${TAG}"
            git clone ssh://aur@aur.archlinux.org/yuzu-mainline-bin.git && cd yuzu-mainline-bin
            wget "https://github.com/linux-gamers/arch-yuzu-mainline/archive/${TAG}.tar.gz"
            VERSION=$(echo ${TAG} | cut -d- -f2)
            sed -i -E "s/_pkgver=.+/_pkgver=${VERSION}/" PKGBUILD
            SHA=$(sha512sum ${TAG}.tar.gz | grep -Eo "(\w+)\s" | cut -d" " -f1)
            sed -i -E "s/sha512sums=.+/sha512sums=\(\'${SHA}\'\)/" PKGBUILD
            ./gensrc.sh
            makepkg -Acsmf
            git commit -am "${TAG}"
            git push

workflows:
  publish-release:
    jobs:
      - release-github:
          filters:
            branches:
              only:
                - ci
      - release-aur:
          requires:
            - release-github
          filters:
            branches:
              only:
                - ci
