version: 2.1

jobs:
  release-github:
    docker:
      - image: circleci/python
    steps:
      - run:
          name: Publishing release to GitHub
          command: |
            echo "$(pwd)"

  release-aur:
    docker:
      - image: linuxgamers/arch-yuzu-build
    steps:
      - attach_workspace:
          at: /tmp/work/shared
      - run:
          name: Publishing release to AUR
          command: |
            git config --global user.name "${GIT_USER}"
            git config --global user.email "${GIT_EMAIL}"
            export TAG=$(cat shared/tag.txt)
            echo "Publishing release: ${TAG}"
            git clone ssh://aur@aur.archlinux.org/yuzu-mainline-bin.git && cd yuzu-mainline-bin
            wget "https://github.com/linux-gamers/arch-yuzu-mainline/archive/${TAG}.tar.gz"
            VERSION=$(echo ${TAG} | cut -d- -f2)
            sed -i -E "s/_pkgver=.+/_pkgver=${VERSION}/" PKGBUILD
            SHA=$(sha512sum ${TAG}.tar.gz | grep -Eo "(\w+)\s" | cut -d" " -f1)
            sed -i -E "s/sha512sums=.+/sha512sums=\(\'${SHA}\'\)/" PKGBUILD
            ./gensrc.sh
            makepkg -Acsmf
            git commit -am "${TAG}"
            git push

workflows:
  publish-release:
    jobs:
      - release-github:
          filters:
            branches:
              only:
                - ci
